'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const {AgentSettings,defaults}=require('../src/agent-settings.cjs');const {FilesystemService}=require('../src/filesystem.cjs');const {Librarian}=require('../src/librarian.cjs');const {SelectedProvider}=require('../src/selected-provider.cjs');const {FileIcons}=require('../src/file-icons.cjs');
const secure={isEncryptionAvailable:()=>true,getSelectedStorageBackend:()=> 'gnome_libsecret',encryptString:value=>Buffer.from('encrypted:'+value),decryptString:bytes=>bytes.toString().replace(/^encrypted:/,'')};
async function fixture(t,safeStorage){const root=await fs.mkdtemp(path.join(os.tmpdir(),'veyl-settings-test-')),home=path.join(root,'home'),stateDir=path.join(home,'app-state');await fs.mkdir(home);const settings=new AgentSettings({stateDir,safeStorage});await settings.initialize();const filesystem=new FilesystemService({home,stateDir,trashRoot:path.join(root,'Trash')});t.after(async()=>{filesystem.cancelAll();await fs.rm(root,{recursive:true,force:true});});return{root,home,stateDir,settings,filesystem};}
async function save(settings,edit,extra={}){const value=settings.public(),agents=structuredClone(value.agents);edit?.(agents);return settings.update({accent:value.accent,agents,version:value.version,...extra});}
const observation=(action,file)=>({action,path:file,query:action==='search'?'auth':null,limit:100,offset:0,sort:'name',direction:'asc'});
const change=(action,file,extra={})=>({action,paths:file?[file]:[],destination:null,name:null,prefix:null,start:null,keepExtension:null,format:null,content:null,...extra});
test('agent archive extraction refuses embedded credential names before output creation; manual extraction stays user controlled',async t=>{const f=await fixture(t),folder=path.join(f.home,'sensitive-source'),archive=path.join(f.home,'private.zip');await fs.mkdir(folder);await fs.writeFile(path.join(folder,'.env'),'fixture');const created=await f.filesystem.mutate({action:'archive-create',paths:[folder],destination:f.home,name:'private.zip',format:'zip'});assert.equal(created.errors.length,0);const blocked=await f.filesystem.mutate({action:'archive-extract',paths:[archive],destination:f.home,name:'agent-output',policyGuard:f.settings.guard('archive-extract',f.settings.policyVersion)});assert.equal(blocked.changes.length,0);assert.match(blocked.errors[0].message,/credential/);await assert.rejects(fs.stat(path.join(f.home,'agent-output')),{code:'ENOENT'});const manual=await f.filesystem.mutate({action:'archive-extract',paths:[archive],destination:f.home,name:'manual-output'});assert.equal(manual.errors.length,0);assert.equal(await fs.readFile(path.join(f.home,'manual-output','sensitive-source','.env'),'utf8'),'fixture');});
test('revocation during awaited destination/parent setup prevents the first write or native transfer',async t=>{const f=await fixture(t),source=path.join(f.home,'before.txt'),destination=path.join(f.home,'out');await fs.writeFile(source,'keep bytes');await fs.mkdir(destination);const original=f.filesystem.directory.bind(f.filesystem);let revoked=false;f.filesystem.directory=async file=>{const result=await original(file);if(file===destination&&!revoked){revoked=true;await save(f.settings,agents=>{agents.librarian.permissions.moveRename=false;});}return result;};const result=await f.filesystem.mutate({action:'move',paths:[source],destination,policyGuard:f.settings.guard('move',f.settings.policyVersion)});assert.equal(result.changes.length,0);assert.equal(result.errors[0].code,'PERMISSION_DENIED');assert.equal(await fs.readFile(source,'utf8'),'keep bytes');await assert.rejects(fs.stat(path.join(destination,'before.txt')),{code:'ENOENT'});f.filesystem.directory=original;const parent=f.filesystem.parentGuard.bind(f.filesystem);f.filesystem.parentGuard=async file=>{const result=await parent(file);if(path.basename(file)==='denied.txt')await save(f.settings,agents=>{agents.librarian.permissions.createEdit=false;});return result;};await assert.rejects(f.filesystem.mutate({action:'new-file',destination:f.home,name:'denied.txt',policyGuard:f.settings.guard('new-file',f.settings.policyVersion)}),{code:'PERMISSION_DENIED'});await assert.rejects(fs.stat(path.join(f.home,'denied.txt')),{code:'ENOENT'});});
test('cross-device fallback cancellation stops further writes/deletions and retains explicit partial output',async t=>{const f=await fixture(t),source=path.join(f.home,'large.bin'),target=path.join(f.home,'partial.bin');await fs.writeFile(source,Buffer.alloc(3*1024*1024,73));f.filesystem.nativeMoves=false;const remove=f.filesystem.removeVerified.bind(f.filesystem);let removed=false;f.filesystem.removeVerified=async(...args)=>{removed=true;return remove(...args);};let calls=0;const guard=()=>{if(++calls>=8)throw Object.assign(new Error('revoked during copy'),{code:'PERMISSION_DENIED'});};await assert.rejects(f.filesystem.transfer(source,target,'move',null,guard),error=>error.code==='PERMISSION_DENIED'&&error.partial.destination===target);assert.equal(removed,false);assert.equal((await fs.stat(source)).size,3*1024*1024);assert.equal(await fs.readFile(source).then(bytes=>bytes.every(value=>value===73)),true);assert.equal((await fs.stat(target)).size,1024*1024);});
test('archive permission is rechecked after setup and before spawning its owned helper',async t=>{const f=await fixture(t),source=path.join(f.home,'plain.txt');await fs.writeFile(source,'plain');let spawned=false;f.filesystem.archives.spawn=()=>{spawned=true;throw new Error('must not start');};const original=f.filesystem.assertParent.bind(f.filesystem);f.filesystem.assertParent=async guard=>{await original(guard);await save(f.settings,agents=>{agents.librarian.permissions.archives=false;});};const result=await f.filesystem.mutate({action:'archive-create',paths:[source],destination:f.home,name:'guarded.zip',format:'zip',policyGuard:f.settings.guard('archive-create',f.settings.policyVersion)});assert.equal(spawned,false);assert.equal(result.changes.length,0);assert.equal(result.errors[0].code,'PERMISSION_DENIED');await assert.rejects(fs.stat(path.join(f.home,'guarded.zip')),{code:'ENOENT'});});
test('permission changes between independent transfers retain truthful partial results and Undo',async t=>{const f=await fixture(t),destination=path.join(f.home,'out');await fs.mkdir(destination);const sources=['a.txt','b.txt'].map(name=>path.join(f.home,name));for(const file of sources)await fs.writeFile(file,path.basename(file));const original=f.filesystem.transfer.bind(f.filesystem);let count=0;f.filesystem.transfer=async(...args)=>{const result=await original(...args);if(++count===1)await save(f.settings,agents=>{agents.librarian.permissions.copy=false;});return result;};const result=await f.filesystem.mutate({action:'copy',paths:sources,destination,policyGuard:f.settings.guard('copy',f.settings.policyVersion)});assert.equal(result.changes.length,1);assert.equal(result.errors[0].code,'PERMISSION_DENIED');assert.equal(result.undoAvailable,true);await f.filesystem.mutate({action:'undo'});for(const source of sources)assert.equal(await fs.readFile(source,'utf8'),path.basename(source));await assert.rejects(fs.stat(path.join(destination,'a.txt')),{code:'ENOENT'});await assert.rejects(fs.stat(path.join(destination,'b.txt')),{code:'ENOENT'});});
test('sensitive descendants are blocked before a folder mutation or archive helper invocation',async t=>{const f=await fixture(t),folder=path.join(f.home,'project');await fs.mkdir(folder);await fs.writeFile(path.join(folder,'.env'),'never-share');const librarian=new Librarian({filesystem:f.filesystem,policy:f.settings}),context=await librarian.context({path:f.home,selection:[],entries:[]});await assert.rejects(librarian.preparePlan([change('archive-create',folder,{destination:f.home,name:'project.zip',format:'zip'})],context,new AbortController().signal),{code:'SENSITIVE'});await assert.rejects(fs.stat(path.join(f.home,'project.zip')),{code:'ENOENT'});assert.equal(await fs.readFile(path.join(folder,'.env'),'utf8'),'never-share');await save(f.settings,agents=>{agents.librarian.permissions.read=false;});let observed=false;f.filesystem.directory=async()=>{observed=true;throw new Error('must not observe');};await assert.rejects(librarian.context({path:f.home,entries:[],selection:[]}),{code:'PERMISSION_DENIED'});assert.equal(observed,false);});
test('defaults retain existing capabilities and Luna/medium, with separately versioned accent persistence',async t=>{const f=await fixture(t);assert.deepEqual(f.settings.data,defaults());const version=f.settings.policyVersion;await save(f.settings,null,{accent:'#17c5ab'});assert.equal(f.settings.policyVersion,version);const loaded=new AgentSettings({stateDir:f.stateDir});await loaded.initialize();assert.equal(loaded.data.accent,'#17c5ab');assert.equal(loaded.data.agents.librarian.provider.model,'gpt-6-luna');assert.equal(loaded.data.agents.librarian.permissions.imageViewing,true);});
test('basic_text and unknown/unavailable Linux backends keep new keys session-only, never plaintext on disk',async t=>{const f=await fixture(t,{...secure,getSelectedStorageBackend:()=> 'basic_text'});await save(f.settings,agents=>{agents.librarian.provider.type='openai-api';},{secret:'test-only'});assert.equal(f.settings.secret('librarian'),'test-only');assert.equal(f.settings.public().secretState.librarian.storage,'session');const disk=await fs.readFile(path.join(f.stateDir,'agent-settings.json'),'utf8');assert.ok(!disk.includes('test-only'));assert.ok(!JSON.stringify(f.settings.public()).includes('test-only'));assert.equal(new AgentSettings({safeStorage:{...secure,getSelectedStorageBackend:()=> 'unknown'}}).secure(),false);assert.equal(new AgentSettings({safeStorage:{...secure,getSelectedStorageBackend:()=>{throw new Error('locked');}}}).secure(),false);});
test('secure secrets are namespaced by agent and API provider; switching and clearing cannot forward vendor keys',async t=>{const f=await fixture(t,secure);await save(f.settings,agents=>{agents.librarian.provider.type='openai-api';},{secret:'openai-fixture'});await save(f.settings,agents=>{agents.librarian.provider={type:'anthropic-api',model:'claude-sonnet-5-5',effort:'medium'};});assert.equal(f.settings.secret('librarian'),null);assert.equal(f.settings.public().secretState.librarian.configured,false);await save(f.settings,null,{secret:'anthropic-fixture'});await save(f.settings,agents=>{agents.iconDesigner.provider={type:'gemini-api',model:'gemini-3.8-flash',effort:'medium'};},{agent:'iconDesigner',secret:'gemini-fixture'});assert.equal(f.settings.secret('librarian'),'anthropic-fixture');assert.equal(f.settings.secret('iconDesigner'),'gemini-fixture');await save(f.settings,null,{clearSecret:true});await save(f.settings,agents=>{agents.librarian.provider={type:'openai-api',model:'gpt-6-luna',effort:'medium'};});assert.equal(f.settings.secret('librarian'),'openai-fixture');await assert.rejects(save(f.settings,agents=>{agents.librarian.provider.type='codex-cli';},{secret:'must-not-auth-cli'}),{code:'SETTINGS'});});
test('locked secure storage preserves ciphertext while applying ordinary settings; corrupt settings fail closed',async t=>{const f=await fixture(t,secure);await save(f.settings,agents=>{agents.librarian.provider.type='openai-api';},{secret:'secure-fixture'});const before=JSON.parse(await fs.readFile(path.join(f.stateDir,'agent-settings.json'),'utf8')).encryptedKeys;const locked=new AgentSettings({stateDir:f.stateDir,safeStorage:{...secure,isEncryptionAvailable:()=>false}});await locked.initialize();assert.equal(locked.public().secretState.librarian.storage,'locked');await save(locked,null,{accent:'#c123fa'});assert.deepEqual(JSON.parse(await fs.readFile(path.join(f.stateDir,'agent-settings.json'),'utf8')).encryptedKeys,before);await fs.writeFile(path.join(f.stateDir,'agent-settings.json'),'invalid');const corrupt=new AgentSettings({stateDir:f.stateDir});await corrupt.initialize();assert.throws(()=>corrupt.require('librarian','read'),{code:'PERMISSION_DENIED'});assert.match(corrupt.public().warning,/disabled/);assert.equal(await fs.readFile(path.join(f.stateDir,'agent-settings.json'),'utf8'),'invalid');});
test('queued mutation and Undo recheck current permission/version; manual explorer remains independent',async t=>{const f=await fixture(t);let release;f.filesystem.queue=new Promise(resolve=>{release=resolve;});const pending=f.filesystem.mutate({action:'new-file',destination:f.home,name:'blocked.txt',policyGuard:f.settings.guard('new-file',f.settings.policyVersion)});const rejected=assert.rejects(pending,{code:'PERMISSION_DENIED'});await save(f.settings,agents=>{agents.librarian.permissions.createEdit=false;});release();await rejected;await assert.rejects(fs.stat(path.join(f.home,'blocked.txt')),{code:'ENOENT'});await f.filesystem.mutate({action:'new-file',destination:f.home,name:'manual.txt'});assert.equal((await fs.stat(path.join(f.home,'manual.txt'))).isFile(),true);const denied=await f.filesystem.mutate({action:'undo',policyGuard:f.settings.guard('undo',f.settings.policyVersion)});assert.equal(denied.changes.length,0);assert.equal(denied.errors[0].code,'PERMISSION_DENIED');assert.equal(await fs.readFile(path.join(f.home,'manual.txt'),'utf8'),'');await f.filesystem.mutate({action:'undo'});await assert.rejects(fs.stat(path.join(f.home,'manual.txt')),{code:'ENOENT'});});
test('mixed plans are denied before binding or mutation, and image denial precedes decoding/provider sharing',async t=>{const f=await fixture(t);const file=path.join(f.home,'safe.txt');await fs.writeFile(file,'safe');const librarian=new Librarian({filesystem:f.filesystem,policy:f.settings,provider:{status:async()=>({available:true}),plan:async()=>{throw new Error('must not invoke');}}});await save(f.settings,agents=>{agents.librarian.permissions.trash=false;agents.librarian.permissions.imageViewing=false;});const context=await librarian.context({path:f.home,entries:[],selection:[]});await assert.rejects(librarian.preparePlan([change('rename',file,{name:'renamed.txt'}),change('trash',file)],context,new AbortController().signal),{code:'PERMISSION_DENIED'});assert.equal(await fs.readFile(file,'utf8'),'safe');await assert.rejects(librarian.runVision('fixture','describe images',context,()=>{},new AbortController().signal,{rename:false}),{code:'PERMISSION_DENIED'});});
test('credential metadata/list/search/properties and aliases stay outside provider context; manual listing remains available',async t=>{const f=await fixture(t);await fs.mkdir(path.join(f.home,'.codex'));await fs.writeFile(path.join(f.home,'.codex','auth.json'),'fixture-do-not-read');await fs.mkdir(f.stateDir);await fs.writeFile(path.join(f.stateDir,'private.json'),'private');await fs.writeFile(path.join(f.home,'safe.txt'),'safe');await fs.writeFile(path.join(f.home,'.env'),'fixture');const alias=path.join(f.home,'normal-alias');await fs.symlink(path.join(f.home,'.codex'),alias);const librarian=new Librarian({filesystem:f.filesystem,policy:f.settings});const entries=(await f.filesystem.list({path:f.home,hidden:true})).entries;assert.ok(entries.some(entry=>entry.name==='.codex'));const context=await librarian.context({path:f.home,hidden:true,selection:[],entries});assert.deepEqual(context.entries.map(entry=>entry.name),['safe.txt']);const list=await librarian.observe(observation('list',f.home),context,'list',new AbortController().signal);assert.deepEqual(list.entries.map(entry=>entry.name),['safe.txt']);const search=await librarian.observe(observation('search',f.home),context,'find auth',new AbortController().signal);assert.equal(search.entries.length,0);await assert.rejects(librarian.observe(observation('properties',alias),context,'properties',new AbortController().signal),{code:'SENSITIVE'});await assert.rejects(librarian.context({path:f.home,selection:[alias],entries:[]}),{code:'SENSITIVE'});await assert.rejects(librarian.preparePlan([change('rename',path.join(f.home,'.env'),{name:'out.txt'})],context,new AbortController().signal),{code:'SENSITIVE'});});
test('known key redaction covers prompt history/result and unsupported settings never fall back',async t=>{const f=await fixture(t);await save(f.settings,agents=>{agents.librarian.provider.type='openai-api';},{secret:'fixture-private-api-value'});const selected=new SelectedProvider(f.settings);let called=false;selected.codex.plan=async()=>{called=true;};await assert.rejects(save(f.settings,agents=>{agents.librarian.provider={type:'unsupported-cli',model:'fixture',effort:'default'};}),{code:'SETTINGS'});assert.equal(f.settings.data.agents.librarian.provider.type,'openai-api');assert.equal(called,false);await save(f.settings,agents=>{agents.librarian.provider={type:'codex-cli',model:'gpt-6-luna',effort:'medium'};});selected.codex.plan=async prompt=>{assert.ok(!prompt.includes('fixture-private-api-value'));return{reply:'fixture-private-api-value',observations:[],views:[],changes:[]};};const result=await selected.plan('history includes fixture-private-api-value');assert.equal(result.reply,'[redacted]');const librarian=new Librarian({filesystem:f.filesystem,policy:f.settings});librarian.remember('user','fixture-private-api-value');assert.equal(librarian.history.at(-1).text,'[redacted]');});
test('public provider choices are exactly the supported five and preserve the Codex default',async t=>{const f=await fixture(t),state=f.settings.public(),providers=['codex-cli','claude-cli','openai-api','anthropic-api','gemini-api'];assert.deepEqual(state.providers,providers);assert.deepEqual(Object.keys(state.providerCatalog),providers);for(const agent of Object.values(state.agents))assert.deepEqual(agent.provider,{type:'codex-cli',model:'gpt-6-luna',effort:'medium'});});
test('unsupported saved provider values fail closed without rewriting stored settings',async t=>{const f=await fixture(t),settings=defaults();settings.agents.librarian.provider={type:'unsupported-cli',model:'fixture',effort:'default'};await fs.mkdir(f.stateDir,{recursive:true});const file=path.join(f.stateDir,'agent-settings.json'),original=JSON.stringify({settings});await fs.writeFile(file,original);const restored=new AgentSettings({stateDir:f.stateDir});const state=await restored.initialize();assert.match(state.warning,/could not be verified/);for(const agent of Object.values(state.agents))assert.ok(Object.values(agent.permissions).every(value=>value===false));assert.equal(await fs.readFile(file,'utf8'),original);await fs.writeFile(path.join(f.home,'manual.txt'),'manual bytes');assert.ok((await f.filesystem.list({path:f.home})).entries.some(entry=>entry.name==='manual.txt'));});
test('generic hidden configuration stores cannot be shared, selected, mutated or extracted by agents',async t=>{const f=await fixture(t),store=path.join(f.home,'.private-config'),metadata=path.join(store,'state.json'),image=path.join(store,'photo.png');await fs.mkdir(store);await fs.writeFile(metadata,'private metadata');await fs.writeFile(image,'private image fixture');await fs.writeFile(path.join(f.home,'ordinary.txt'),'ordinary');const librarian=new Librarian({filesystem:f.filesystem,policy:f.settings}),entries=(await f.filesystem.list({path:f.home,hidden:true})).entries;assert.ok(entries.some(entry=>entry.name==='.private-config'));const context=await librarian.context({path:f.home,hidden:true,entries,selection:[]});assert.deepEqual(context.entries.map(entry=>entry.name),['ordinary.txt']);for(const action of ['list','images','search','properties'])await assert.rejects(librarian.observe(observation(action,store),context,'inspect configuration',new AbortController().signal),{code:'SENSITIVE'});await assert.rejects(librarian.context({path:f.home,selection:[image],entries:[]}),{code:'SENSITIVE'});await assert.rejects(librarian.preparePlan([change('rename',metadata,{name:'renamed.json'})],context,new AbortController().signal),{code:'SENSITIVE'});assert.equal(await fs.readFile(metadata,'utf8'),'private metadata');const archive=path.join(f.home,'hidden-store.zip');const created=await f.filesystem.mutate({action:'archive-create',paths:[store],destination:f.home,name:'hidden-store.zip',format:'zip'});assert.equal(created.errors.length,0);const blocked=await f.filesystem.mutate({action:'archive-extract',paths:[archive],destination:f.home,name:'agent-hidden-output',policyGuard:f.settings.guard('archive-extract',f.settings.policyVersion)});assert.equal(blocked.changes.length,0);assert.match(blocked.errors[0].message,/credential\/configuration/);await assert.rejects(fs.stat(path.join(f.home,'agent-hidden-output')),{code:'ENOENT'});const manual=await f.filesystem.mutate({action:'archive-extract',paths:[archive],destination:f.home,name:'manual-hidden-output'});assert.equal(manual.errors.length,0);assert.equal(await fs.readFile(path.join(f.home,'manual-hidden-output','.private-config','state.json'),'utf8'),'private metadata');});
test('icon permissions block new generation without poisoning cached or built-in icons',async t=>{const f=await fixture(t);let calls=0;const registry=new FileIcons({stateDir:f.stateDir,canGenerate:()=>f.settings.data.agents.iconDesigner.permissions.designIcons,provider:{designIcons:async()=>{calls++;}},debounce:1});await save(f.settings,agents=>{agents.iconDesigner.permissions.designIcons=false;});assert.equal(registry.resolve(['ext:novel'])[0].state,'disabled');assert.equal(registry.queue.size,0);assert.equal(registry.resolve(['ext:txt'])[0].state,'builtin');await registry.pump();assert.equal(calls,0);await registry.shutdown();});

test('ordinary hidden files stay usable while multi-dot hidden directories and aliases never become agent scope',async t=>{
 const f=await fixture(t),file=path.join(f.home,'.hidden.txt'),store=path.join(f.home,'.private.config.v2'),alias=path.join(f.home,'ordinary-alias');
 await fs.writeFile(file,'ordinary hidden text');await fs.mkdir(store);await fs.writeFile(path.join(store,'state.json'),'private state');await fs.symlink(store,alias);
 for(const name of ['.env','.npmrc','.netrc'])await fs.writeFile(path.join(f.home,name),'credential fixture');
 const librarian=new Librarian({filesystem:f.filesystem,policy:f.settings}),entries=(await f.filesystem.list({path:f.home,hidden:true})).entries;
 const context=await librarian.context({path:f.home,hidden:true,selection:[file],contentPaths:[file],entries});assert.deepEqual(context.entries.map(entry=>entry.name),['.hidden.txt']);
 const list=await librarian.observe(observation('list',f.home),context,'list hidden files',new AbortController().signal);assert.deepEqual(list.entries.map(entry=>entry.name),['.hidden.txt']);
 const read=await librarian.observe(observation('read-text',file),context,'read selected text',new AbortController().signal);assert.equal(read.text,'ordinary hidden text');
 const plan=await librarian.preparePlan([change('rename',file,{name:'.renamed.txt'})],context,new AbortController().signal);assert.deepEqual(plan.steps[0].targets,[path.join(f.home,'.renamed.txt')]);
 for(const directory of [store,alias]){
  assert.equal(await librarian.shareable(directory),false);await assert.rejects(librarian.context({path:directory,entries:[],selection:[]}),{code:'SENSITIVE'});await assert.rejects(librarian.grantScope(directory),{code:'SENSITIVE'});
  for(const action of ['list','search','properties','images'])await assert.rejects(librarian.observe(observation(action,directory),context,'inspect folder',new AbortController().signal),{code:'SENSITIVE'});
 }
 for(const name of ['.env','.npmrc','.netrc']){const credential=path.join(f.home,name);assert.equal(await librarian.shareable(credential),false);await assert.rejects(librarian.context({path:f.home,hidden:true,entries:[],selection:[credential]}),{code:'SENSITIVE'});}
 const search=await librarian.observe({...observation('search',f.home),query:'state'},context,'find state',new AbortController().signal);assert.equal(search.entries.length,0);
 await assert.rejects(librarian.preparePlan([change('new-folder',null,{destination:f.home,name:'.new.config.v2'})],context,new AbortController().signal),{code:'SENSITIVE'});
 const directory=path.join(f.home,'ordinary-folder');await fs.mkdir(directory);await assert.rejects(librarian.preparePlan([change('rename',directory,{name:'.looks.like.txt'})],context,new AbortController().signal),{code:'SENSITIVE'});
 assert.equal(await fs.readFile(file,'utf8'),'ordinary hidden text');assert.equal(await fs.readFile(path.join(store,'state.json'),'utf8'),'private state');
});

test('agent archive extraction distinguishes ordinary hidden files from multi-dot hidden directory members',async t=>{
 const f=await fixture(t),file=path.join(f.home,'.hidden.txt'),store=path.join(f.home,'.private.config.v2');await fs.writeFile(file,'hidden bytes');await fs.mkdir(store);
 for(const [source,archiveName,output,blocked] of [[file,'ordinary-hidden.zip','ordinary-output',false],[store,'hidden-directory.zip','blocked-output',true]]){
  const created=await f.filesystem.mutate({action:'archive-create',paths:[source],destination:f.home,name:archiveName,format:'zip'});assert.equal(created.errors.length,0);
  const result=await f.filesystem.mutate({action:'archive-extract',paths:[path.join(f.home,archiveName)],destination:f.home,name:output,policyGuard:f.settings.guard('archive-extract',f.settings.policyVersion)});
  if(blocked){assert.equal(result.changes.length,0);assert.match(result.errors[0].message,/credential\/configuration/);await assert.rejects(fs.stat(path.join(f.home,output)),{code:'ENOENT'});}
  else{assert.equal(result.errors.length,0);assert.equal(await fs.readFile(path.join(f.home,output,'.hidden.txt'),'utf8'),'hidden bytes');}
 }
});

test('dependent directory outputs retain their type and reject a hidden rename before any mutation',async t=>{
 const f=await fixture(t),source=path.join(f.home,'source-folder'),destination=path.join(f.home,'copies'),copied=path.join(destination,'source-folder');await fs.mkdir(source);await fs.mkdir(destination);await fs.writeFile(path.join(source,'note.txt'),'preserved source');
 const librarian=new Librarian({filesystem:f.filesystem,policy:f.settings}),context=await librarian.context({path:f.home,entries:[],selection:[]}),signal=new AbortController().signal;
 const copy=change('copy',source,{destination});await assert.rejects(librarian.preparePlan([copy,change('rename',copied,{name:'.private.config.v2'})],context,signal),{code:'SENSITIVE'});
 assert.equal(await fs.readFile(path.join(source,'note.txt'),'utf8'),'preserved source');await assert.rejects(fs.stat(copied),{code:'ENOENT'});await assert.rejects(fs.stat(path.join(destination,'.private.config.v2')),{code:'ENOENT'});
 const ordinary=await librarian.preparePlan([copy,change('rename',copied,{name:'renamed-folder'})],context,signal);assert.equal(ordinary.steps.length,2);assert.deepEqual(ordinary.steps[1].targets,[path.join(destination,'renamed-folder')]);await assert.rejects(fs.stat(copied),{code:'ENOENT'});
});
