'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');const {EventEmitter}=require('node:events');
const {sandboxEnvironment,validateHelper,assertSandboxArguments}=require('../scripts/sandbox.cjs');const {launch}=require('../scripts/start.cjs');const {installDesktop,desktopEntry,quoteExec,ID,LEGACY_ID}=require('../scripts/install-desktop.cjs');
function metadata({file=false,uid=0,gid=0,mode=file?0o4755:0o755,link=false}={}){return {uid,gid,mode,isFile:()=>file&&!link,isDirectory:()=>!file&&!link,isSymbolicLink:()=>link};}
function helperStat(changes={}){return async file=>changes[file]??metadata({file:file.endsWith('chrome-sandbox')});}
test('sandbox helper requires root setuid regular file and safe full parent chain',async()=>{
 const helper='/opt/google/chrome/chrome-sandbox';assert.equal(await validateHelper(helper,{lstat:helperStat()}),helper);
 for(const bad of [metadata({file:true,uid:1000}),metadata({file:true,mode:0o755}),metadata({file:true,mode:0o4777}),metadata({file:true,link:true})])await assert.rejects(validateHelper(helper,{lstat:helperStat({[helper]:bad})}),{code:'SANDBOX_SETUP'});
 for(const bad of [metadata({mode:0o777}),metadata({uid:1000}),metadata({link:true})])await assert.rejects(validateHelper(helper,{lstat:helperStat({'/opt/google':bad})}),{code:'SANDBOX_SETUP'});
});
test('resolver selects existing trusted helper, preserves auth/env, and refuses invalid explicit choice',async()=>{
 const root='/project',bundled=path.join(root,'node_modules/electron/dist/chrome-sandbox');const lstat=helperStat({[bundled]:metadata({file:true,uid:1000,mode:0o755})});
 const original={PATH:'/usr/bin',CODEX_HOME:'/private/config',OPENAI_API_KEY:'fixture-only',ELECTRON_RUN_AS_NODE:'1'};
 const resolved=await sandboxEnvironment({env:original,projectRoot:root,lstat});assert.equal(resolved.CHROME_DEVEL_SANDBOX,'/opt/google/chrome/chrome-sandbox');assert.equal(resolved.CODEX_HOME,original.CODEX_HOME);assert.equal(resolved.OPENAI_API_KEY,original.OPENAI_API_KEY);assert.equal(resolved.ELECTRON_RUN_AS_NODE,undefined);assert.equal(original.ELECTRON_RUN_AS_NODE,'1');
 await assert.rejects(sandboxEnvironment({env:{CHROME_DEVEL_SANDBOX:bundled},projectRoot:root,lstat}),/Configured CHROME_DEVEL_SANDBOX was refused/);
 await assert.rejects(sandboxEnvironment({env:{},projectRoot:root,lstat:async()=>{throw Object.assign(new Error('missing'),{code:'ENOENT'});}}),/will not disable sandboxing/);
});
test('sandbox-disabling argv variants are rejected and launcher emits fixed safe argv/environment',async t=>{
 for(const arg of ['--no-sandbox','--disable-setuid-sandbox=true','--disable-gpu-sandbox','--single-process'])assert.throws(()=>assertSandboxArguments([arg]),{code:'SANDBOX_SETUP'});
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'systemus-launch-test-'));await fs.mkdir(path.join(root,'node_modules/electron/dist'),{recursive:true});await fs.writeFile(path.join(root,'node_modules/electron/dist/electron'),'fixture',{mode:0o755});t.after(()=>fs.rm(root,{recursive:true,force:true}));
 let captured;const child=await launch({projectRoot:root,args:[],env:{PATH:'/usr/bin'},resolveEnvironment:async({env})=>({...env,CHROME_DEVEL_SANDBOX:'/trusted/helper'}),spawnImpl:(executable,args,options)=>{captured={executable,args,options};return new EventEmitter();}});
 assert.ok(child);assert.deepEqual(captured.args,[root,'--class=io.github.SketchOTP.VEYL']);assert.equal(captured.options.shell,false);assert.equal(captured.options.cwd,root);assert.ok(captured.options.env.PATH.split(path.delimiter).includes(path.join(os.homedir(),'.local','bin')));assert.equal(captured.options.env.CHROME_DEVEL_SANDBOX,'/trusted/helper');
 await assert.rejects(launch({projectRoot:root,args:['--no-sandbox']}),{code:'SANDBOX_SETUP'});
});
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'systemus-desktop-install-'));const project=path.join(root,'Project with spaces'),home=path.join(root,'home'),desktop=path.join(home,'Desktop with spaces');await fs.mkdir(path.join(project,'assets'),{recursive:true});await fs.mkdir(path.join(project,'scripts'));await fs.copyFile(path.resolve('assets',`${ID}.desktop.in`),path.join(project,'assets',`${ID}.desktop.in`));await fs.copyFile(path.resolve('assets/veyl.svg'),path.join(project,'assets/veyl.svg'));await fs.writeFile(path.join(project,'scripts/start'),'fixture');t.after(()=>fs.rm(root,{recursive:true,force:true}));return {root,project,home,desktop};}
test('desktop install honors XDG paths/spaces, absolute Node, icon readback, and managed-only replacement',async t=>{
 const f=await fixture(t),env={HOME:f.home,XDG_DATA_HOME:path.join(f.home,'Data with spaces')};const args={env,projectRoot:f.project,nodePath:process.execPath,desktopDirectory:f.desktop};
 const result=await installDesktop(args);const entry=await fs.readFile(result.applicationsEntry,'utf8');assert.ok(entry.includes(`Exec=${quoteExec(process.execPath)} ${quoteExec(path.join(f.project,'scripts/start'))}`));assert.ok(entry.includes(`Icon=${result.icon}\n`));assert.ok(!entry.includes('MimeType='));assert.ok(!entry.includes('%U'));assert.ok(!entry.includes('%F'));assert.equal(await fs.readFile(result.desktopEntry,'utf8'),entry);assert.equal((await fs.stat(result.desktopEntry)).mode&0o777,0o755);assert.ok((await fs.readFile(result.icon,'utf8')).includes('<title>VEYL</title>'));
 assert.deepEqual(await installDesktop(args),result);await fs.writeFile(result.applicationsEntry,'[Desktop Entry]\nName=Unrelated\n');await assert.rejects(installDesktop(args),/Unmanaged launcher/);assert.equal(await fs.readFile(result.applicationsEntry,'utf8'),'[Desktop Entry]\nName=Unrelated\n');
});
test('desktop resolves actual XDG desktop via fixed command, and encodes literal Exec metacharacters without shell expansion',async t=>{
 const f=await fixture(t);let command;const result=await installDesktop({env:{HOME:f.home},projectRoot:f.project,nodePath:process.execPath,execImpl:async(executable,args)=>{command={executable,args};return {stdout:f.desktop+'\n'};}});assert.deepEqual(command,{executable:'/usr/bin/xdg-user-dir',args:['DESKTOP']});assert.equal(path.dirname(result.desktopEntry),f.desktop);
 const encoded=quoteExec('/tmp/space $`"\\%f');assert.ok(encoded.includes('%%f'));assert.ok(encoded.includes('\\\\$'));assert.ok(encoded.includes('\\\\`'));assert.ok(encoded.includes('\\\\"'));assert.ok(encoded.includes('\\\\\\\\'));assert.throws(()=>quoteExec('/tmp/path\nextra'));
 const text=await desktopEntry({projectRoot:f.project,nodePath:process.execPath,iconPath:result.icon});assert.ok(text.includes(`StartupWMClass=${ID}\n`));
});
test('desktop migration removes only marked regular entries with exact checkout path and launch command',async t=>{
 const f=await fixture(t),args={env:{HOME:f.home},projectRoot:f.project,nodePath:process.execPath,desktopDirectory:f.desktop};const installed=await installDesktop(args),oldApplication=path.join(path.dirname(installed.applicationsEntry),LEGACY_ID+'.desktop'),oldDesktop=path.join(f.desktop,LEGACY_ID+'.desktop');const text=await fs.readFile(installed.applicationsEntry,'utf8');await fs.writeFile(oldApplication,text.replace('Name=VEYL','Name=SYSTEMUS'));await fs.writeFile(oldDesktop,text);const result=await installDesktop(args);assert.deepEqual(result.migration.removed,[oldApplication,oldDesktop]);for(const file of [oldApplication,oldDesktop])await assert.rejects(fs.lstat(file),{code:'ENOENT'});
 await fs.writeFile(oldApplication,text.replace(`Path=${f.project}`,`Path=${f.root}/different`));await fs.writeFile(oldDesktop,text.replace('X-SYSTEMUS-Managed=true','X-SYSTEMUS-Managed=false'));const preserved=await installDesktop(args);assert.deepEqual(preserved.migration.preserved,[oldApplication,oldDesktop]);assert.match(await fs.readFile(oldDesktop,'utf8'),/Managed=false/);assert.match(await fs.readFile(oldApplication,'utf8'),/different/);
 await fs.unlink(oldDesktop);await fs.symlink(installed.applicationsEntry,oldDesktop);const linkResult=await installDesktop(args);assert.ok(linkResult.migration.preserved.includes(oldDesktop));assert.equal((await fs.lstat(oldDesktop)).isSymbolicLink(),true);assert.equal(await fs.readFile(installed.applicationsEntry,'utf8'),text);
});
test('another checkout managed VEYL entry is not overwritten and legacy exact Path alone cannot authorize removal',async t=>{
 const f=await fixture(t),args={env:{HOME:f.home},projectRoot:f.project,nodePath:process.execPath,desktopDirectory:f.desktop};const installed=await installDesktop(args),text=await fs.readFile(installed.applicationsEntry,'utf8'),other=text.replace(`Path=${f.project}`,`Path=${f.root}/other`);await fs.writeFile(installed.applicationsEntry,other);await assert.rejects(installDesktop(args),/another checkout/);assert.equal(await fs.readFile(installed.applicationsEntry,'utf8'),other);await fs.writeFile(installed.applicationsEntry,text);const old=path.join(f.desktop,LEGACY_ID+'.desktop'),bad=text.replace('Exec=','Exec="/different/app" ');await fs.writeFile(old,bad);const result=await installDesktop(args);assert.deepEqual(result.migration.preserved,[old]);assert.equal(await fs.readFile(old,'utf8'),bad);
});
