'use strict';
const fs=require('node:fs/promises');const {createReadStream,constants}=require('node:fs');const path=require('node:path');const {createHash}=require('node:crypto');
// Positive exact-file allowlist. Adding a runtime module requires a deliberate review here.
const APP_FILES=Object.freeze([
 'package.json','README.md','LICENSE','PRIVACY.md','SECURITY.md','CHANGELOG.md','assets/veyl.png','assets/veyl.svg',
 'assets/banner.svg','assets/screenshots/explorer.png','assets/screenshots/settings.png','assets/screenshots/image-preview.png',
 'src/agent-settings.cjs','src/api-provider.cjs','src/archive_helper.py','src/archives.cjs','src/claude-provider.cjs',
 'src/codex-provider.cjs','src/file-clipboard.cjs','src/file-icon-schema.cjs','src/file-icons.cjs','src/file-type-catalog.cjs',
 'src/filesystem.cjs','src/folder-watch.cjs','src/image-decoder.cjs','src/librarian-images.cjs','src/librarian-schema.cjs',
 'src/librarian.cjs','src/main.cjs','src/preload.cjs','src/provider-catalog.cjs','src/provider-common.cjs',
 'src/selected-provider.cjs','src/sensitive-paths.cjs','src/text-edits.cjs',
 'src/renderer/app.js','src/renderer/file-type-icons.js','src/renderer/icons.js','src/renderer/image-decoder.html',
 'src/renderer/image-decoder.js','src/renderer/index.html','src/renderer/settings.js','src/renderer/styles.css'
]);
async function inventory(root){const files=[];async function visit(dir,relative=''){for(const item of await fs.readdir(dir,{withFileTypes:true})){const name=relative?`${relative}/${item.name}`:item.name;const file=path.join(dir,item.name);if(item.isSymbolicLink())throw new Error(`Release payload must not contain symlinks: ${name}`);if(item.isDirectory())await visit(file,name);else if(item.isFile())files.push(name);else throw new Error(`Unsupported release payload entry: ${name}`);if(files.length>1000)throw new Error('Unexpected release payload size.');}}await visit(root);return files.sort();}
async function verifyApp(root){const actual=await inventory(root),expected=[...APP_FILES].sort();if(JSON.stringify(actual)!==JSON.stringify(expected)){const unexpected=actual.filter(file=>!expected.includes(file)),missing=expected.filter(file=>!actual.includes(file));throw new Error(`Release allowlist mismatch; unexpected=${unexpected.join(',')} missing=${missing.join(',')}`);}const metadata=JSON.parse(await fs.readFile(path.join(root,'package.json'),'utf8'));if(metadata.name!=='veyl'||metadata.version!=='1.0.0'||metadata.main!=='src/main.cjs'||metadata.license!=='MIT')throw new Error('Incorrect release metadata.');const hashes={};for(const file of actual)hashes[file]=createHash('sha256').update(await fs.readFile(path.join(root,file))).digest('hex');return hashes;}
async function verifyELF(file){const handle=await fs.open(file,constants.O_RDONLY|constants.O_NOFOLLOW|constants.O_NONBLOCK);try{const stat=await handle.stat(),header=Buffer.alloc(20);if(!stat.isFile()||stat.size<20)throw new Error('Bundled executable is not a regular ELF64 file.');await handle.read(header,0,header.length,0);if(!header.subarray(0,5).equals(Buffer.from([127,69,76,70,2]))||header[5]!==1||header.readUInt16LE(18)!==62)throw new Error('Bundled executable must be Linux x86-64 ELF, not a launcher or another architecture.');}finally{await handle.close();}}
async function fileHash(file){const hash=createHash('sha256');for await(const chunk of createReadStream(file))hash.update(chunk);return hash.digest('hex');}
async function verifyPackage(root,{manifest=true}={}){root=path.resolve(root);const hashes=await verifyApp(path.join(root,'resources/app'));for(const file of ['launch-veyl','sandbox-helper.sh','veyl','veyl-bin','chrome-sandbox']){const stat=await fs.lstat(path.join(root,file));if(!stat.isFile()||stat.isSymbolicLink())throw new Error(`Required package file is not regular: ${file}`);if(['launch-veyl','sandbox-helper.sh','veyl','veyl-bin'].includes(file)){if((stat.mode&0o777)!==0o755)throw new Error(`Launcher/executable mode must be755: ${file}`);hashes[`../${file}`]=await fileHash(path.join(root,file));}}
 await verifyELF(path.join(root,'veyl-bin'));if(!(await fs.readFile(path.join(root,'veyl'))).equals(await fs.readFile(path.join(root,'launch-veyl'))))throw new Error('Generated desktop entry must target the identical secure launcher.');
 if(manifest){const saved=JSON.parse(await fs.readFile(path.join(root,'resources/release-manifest.json'),'utf8'));if(saved.version!=='1.0.0'||JSON.stringify(saved.sha256)!==JSON.stringify(hashes))throw new Error('Release readback differs from the generated manifest.');}return {version:'1.0.0',appFiles:APP_FILES.length,sha256:hashes};}
module.exports={APP_FILES,inventory,verifyApp,verifyPackage,verifyELF};
