'use strict';
const fs=require('node:fs/promises');const {constants}=require('node:fs');const {TextDecoder}=require('node:util');const {identity}=require('./filesystem.cjs');const {sensitive}=require('./sensitive-paths.cjs');
const LIMIT=128*1024;
function fail(message,code='TEXT_EDIT'){throw Object.assign(new Error(message),{code});}
function textBytes(value){if(typeof value!=='string'||!value.isWellFormed()||/[\0-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(value))fail('Text edits require well-formed UTF-8 text without binary control characters.','TEXT_FORMAT');const bytes=Buffer.from(value,'utf8');if(bytes.length>LIMIT)fail('Text editing is limited to 128 KiB per file.','TEXT_LIMIT');return bytes;}
function decode(bytes){let text;try{text=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(bytes);}catch{fail('The existing file is not valid UTF-8. No text edit was applied.','TEXT_FORMAT');}textBytes(text);return text;}
class TextEdits{
 constructor(service){this.fs=service;this.recoveryBackups=[];}
 async replace(file,bytes,{expected,guard=()=>{},signal,sourceGuard,original}={}){
  const check=()=>{if(signal?.aborted)fail('Text edit cancelled; inspect reported partial results and supported Undo.','CANCELLED');guard();};check();if(!Buffer.isBuffer(bytes)||bytes.length>LIMIT)fail('Text edit output exceeds 128 KiB.','TEXT_LIMIT');decode(bytes);
  file=await this.fs.canonical(file);check();this.fs.protect(file);if(sensitive(file))fail('Credential files cannot be edited by the agent.','SENSITIVE');await sourceGuard?.(file);check();if(!expected)fail('Text edits require an exact original file identity.','CHANGED');
  const parent=await this.fs.parentGuard(file);let handle,before,changed=false,signature,ours;
  try{
   await this.fs.assertParent(parent);check();handle=await fs.open(file,constants.O_RDWR|constants.O_NOFOLLOW|constants.O_NONBLOCK);const stat=await handle.stat();if(!stat.isFile()||stat.nlink!==1)fail('Only regular files without hard links can be edited.','UNSUPPORTED');if(stat.size>LIMIT)fail('Text editing is limited to 128 KiB per file.','TEXT_LIMIT');if(identity(stat)!==expected)fail('Text file changed before editing.','CHANGED');
   check();before=Buffer.alloc(stat.size);let read=0;while(read<before.length){check();const result=await handle.read(before,read,before.length-read,read);if(!result.bytesRead)fail('Text file changed during original-byte capture.','CHANGED');read+=result.bytesRead;}decode(before);if(original&&!before.equals(original))fail('Edited content changed; Undo will not overwrite it.','CHANGED');signature=expected;ours=Buffer.from(before);
   const verify=async()=>{check();await this.fs.assertParent(parent);await this.fs.assertEntry(file,signature);if(identity(await handle.stat())!==signature)fail('The opened text file changed while editing.','CHANGED');check();};
   await verify();let offset=0;while(offset<bytes.length){await verify();const result=await handle.write(bytes,offset,Math.min(32768,bytes.length-offset),offset);if(!result.bytesWritten)fail('The file write did not make progress.','WRITE');changed=true;if(offset+result.bytesWritten>ours.length){const extended=Buffer.alloc(offset+result.bytesWritten);ours.copy(extended);ours=extended;}bytes.copy(ours,offset,offset,offset+result.bytesWritten);offset+=result.bytesWritten;signature=identity(await handle.stat());}
   await verify();if((await handle.stat()).size!==bytes.length){check();await handle.truncate(bytes.length);changed=true;ours=Buffer.from(bytes);signature=identity(await handle.stat());}await handle.sync();await verify();
   const current=Buffer.alloc(bytes.length+1);let readBack=0;while(readBack<current.length){check();const read=await handle.read(current,readBack,current.length-readBack,readBack);if(!read.bytesRead)break;readBack+=read.bytesRead;}await verify();if(readBack!==bytes.length||!current.subarray(0,readBack).equals(bytes))fail('Text edit verification differed from the requested bytes.','CHANGED');check();return{target:file,signature,original:before,edited:Buffer.from(bytes),changed};
  }catch(e){if(changed&&handle&&before){let current;try{if(e.code==='CHANGED')throw e;const stat=await handle.stat();if(identity(stat)!==signature||stat.size!==ours.length||stat.size>LIMIT)fail('Recovery identity changed.','CHANGED');await this.fs.assertParent(parent);await this.fs.assertEntry(file,signature);const captured=Buffer.alloc(stat.size);let offset=0;while(offset<captured.length){const read=await handle.read(captured,offset,captured.length-offset,offset);if(!read.bytesRead)fail('Recovery read changed.','CHANGED');offset+=read.bytesRead;}if(!captured.equals(ours)||identity(await handle.stat())!==signature)fail('Recovery bytes changed.','CHANGED');await this.fs.assertEntry(file,signature);current={target:file,signature,original:before,edited:captured,changed:true};}catch{}if(!current){this.recoveryBackups.push({target:file,original:Buffer.from(before),originalIdentity:expected});this.recoveryBackups=this.recoveryBackups.slice(-20);}e.editUndo=current;e.partial={path:file,originalRetained:true,undoEligible:Boolean(current),message:current?'A partial app-owned text write remains. Guarded Undo can restore original bytes while the entry still matches.':'External change or replacement prevents automatic Undo. Original bytes are retained privately in bounded session memory; external data will not be overwritten.'};}throw e;
  }finally{await handle?.close().catch(()=>{});}
 }
 async apply(request){request.policyGuard?.();const paths=request.paths;if(!Array.isArray(paths)||paths.length!==1)fail('Edit one explicit file per step.','TEXT_EDIT');const bytes=textBytes(request.content);const file=await this.fs.canonical(paths[0]);return this.replace(file,bytes,{expected:request.expectedIdentities?.[file],guard:request.policyGuard,signal:request.signal,sourceGuard:request.sourceGuard});}
 async undo(item,guard){return this.replace(item.target,item.original,{expected:item.signature,original:item.edited,guard});}
}
module.exports={TextEdits,LIMIT,textBytes,decode};
