const labels={read:'Read, list & search',imageViewing:'View image pixels',createEdit:'Create & edit text',copy:'Copy & duplicate',moveRename:'Move & rename',trash:'Recoverable Trash',archives:'Create & extract archives',restoreUndo:'Restore & supported Undo',designIcons:'Design new type icons'};
const providers={'codex-cli':'Codex CLI · existing login','claude-cli':'Claude CLI','openai-api':'OpenAI API','anthropic-api':'Anthropic API','gemini-api':'Gemini API'};
function rgb(hex){return hex.slice(1).match(/../g).map(v=>parseInt(v,16));}
function hex(values){return '#'+values.map(v=>Math.round(v).toString(16).padStart(2,'0')).join('');}
function hsv(value){const [r,g,b]=rgb(value).map(v=>v/255),max=Math.max(r,g,b),min=Math.min(r,g,b),delta=max-min;let hue=delta?(max===r?(g-b)/delta%6:max===g?(b-r)/delta+2:(r-g)/delta+4)*60:0;return[(hue+360)%360,max?delta/max:0,max];}
function fromHSV(h,s,v){const c=v*s,x=c*(1-Math.abs(h/60%2-1)),m=v-c,[r,g,b]=h<60?[c,x,0]:h<120?[x,c,0]:h<180?[0,c,x]:h<240?[0,x,c]:h<300?[x,0,c]:[c,0,x];return hex([r,g,b].map(n=>(n+m)*255));}
export function applyAccent(value){if(!/^#[0-9a-f]{6}$/i.test(value))return;const root=document.documentElement.style,[r,g,b]=rgb(value);let button=[r,g,b];const luminance=values=>values.map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((n,v,i)=>n+v*[.2126,.7152,.0722][i],0);while(luminance(button)>.18)button=button.map(v=>v*.9);root.setProperty('--purple',value);root.setProperty('--purple-bright',hex(button));root.setProperty('--purple-control',hex(button));root.setProperty('--purple-border',hex([r,g,b].map(v=>v*.72)));root.setProperty('--purple-dim',hex([r,g,b].map(v=>v*.22)));root.setProperty('--purple-hover',hex([r,g,b].map(v=>v*.35)));root.setProperty('--glow',value+'40');}
export async function initializeSettings(api,onChanged){
 let state=await api.agentSettings();applyAccent(state.accent);let draft,agent='librarian',hue,saturation,brightness;
 const $=id=>document.getElementById(id),modal=$('settings-dialog'),fields=$('agent-permissions'),model=$('settings-model'),effort=$('settings-effort'),provider=$('settings-provider'),secret=$('settings-secret'),clear=$('settings-clear-secret');
 const updateColor=()=>{const color=fromHSV(hue,saturation,brightness);draft.accent=color;$('settings-accent').value=color;$('accent-dial').style.setProperty('--dial-angle',hue+'deg');$('accent-dial').setAttribute('aria-valuenow',String(Math.round(hue)));$('accent-dial').setAttribute('aria-valuetext',color);$('accent-preview').style.background=color;};
 const colorFromHex=()=>{if(/^#[0-9a-f]{6}$/i.test($('settings-accent').value)){[hue,saturation,brightness]=hsv($('settings-accent').value);$('accent-saturation').value=Math.round(saturation*100);$('accent-brightness').value=Math.round(brightness*100);updateColor();}};
 const capture=()=>{if(!draft)return;draft.agents[agent].provider={type:provider.value,model:model.value,effort:effort.value};};
 const modelControls=()=>{const info=state.providerCatalog[provider.value];$('settings-model-options').replaceChildren(...Object.keys(info.models).map(value=>{const node=document.createElement('option');node.value=value;return node;}));const previous=effort.value,allowed=info.models[model.value]||(info.custom?['default']:[]);effort.replaceChildren(...allowed.map(value=>{const node=document.createElement('option');node.value=value;node.textContent=value==='default'?'Default · no override':value;return node;}));effort.value=allowed.includes(previous)?previous:allowed.includes(info.defaultEffort)?info.defaultEffort:allowed[0]||'';};
 const render=()=>{
  const config=draft.agents[agent];provider.replaceChildren(...state.providers.map(type=>{const node=document.createElement('option');node.value=type;node.textContent=providers[type];return node;}));provider.value=config.provider.type;model.value=config.provider.model;effort.value=config.provider.effort;
  modelControls();effort.value=config.provider.effort;
  fields.replaceChildren(...state.capabilities[agent].map(key=>{const label=document.createElement('label'),input=document.createElement('input'),text=document.createElement('span');input.type='checkbox';input.checked=config.permissions[key];input.dataset.permission=key;input.onchange=()=>{draft.agents[agent].permissions[key]=input.checked;};text.textContent=labels[key];label.append(input,text);return label;}));
  secret.value='';clear.checked=false;const apiMode=provider.value.endsWith('-api');$('settings-secret-group').hidden=!apiMode;
  const sameProvider=provider.value===state.agents[agent].provider.type,stored=sameProvider?state.secretState[agent]:{storage:'none',configured:false};$('settings-secret-state').textContent=`${stored.configured?'Key configured · '+stored.storage:'No key configured'}. ${state.secureStorage?'Encrypted OS storage available.':'Secure OS storage unavailable: new keys are session-only.'}`;
  $('settings-provider-status').textContent='';$('settings-provider-note').textContent=apiMode?'Your own selected vendor key only. API use may incur vendor charges. Suggestions do not guarantee account availability; custom models use default effort and cannot receive images.':`Uses your existing ${providers[provider.value]} installation and saved login. No authentication is changed. ${provider.value==='claude-cli'?'Requires verified personal Pro/Max status; managed or unknown policy is blocked. ':''}Suggestions do not guarantee account availability; no model fallback is used.`;
 };
 $('settings-open').onclick=()=>{draft={accent:state.accent,agents:structuredClone(state.agents)};agent='librarian';$('settings-agent').value=agent;[hue,saturation,brightness]=hsv(draft.accent);$('accent-saturation').value=Math.round(saturation*100);$('accent-brightness').value=Math.round(brightness*100);updateColor();render();$('settings-error').textContent=state.warning||'';modal.showModal();};
 $('settings-agent').onchange=()=>{capture();agent=$('settings-agent').value;render();};
 provider.onchange=()=>{const info=state.providerCatalog[provider.value];draft.agents[agent].provider={type:provider.value,model:info.defaultModel,effort:info.defaultEffort};render();};model.oninput=()=>{modelControls();capture();};effort.onchange=capture;
 $('settings-provider-docs').onclick=()=>api.providerDocs(provider.value).catch(error=>{$('settings-error').textContent=error.message;});
 $('settings-provider-check').onclick=async()=>{const button=$('settings-provider-check');button.disabled=true;try{if(JSON.stringify({type:provider.value,model:model.value,effort:effort.value})!==JSON.stringify(state.agents[agent].provider)||secret.value||clear.checked)throw new Error('Save this configuration first. Connection checks use only the saved provider, never unsaved keys.');const result=await api.providerStatus(agent);$('settings-provider-status').textContent=result.message;}catch(error){$('settings-provider-status').textContent=error.message;}finally{button.disabled=false;}};
 $('settings-accent').oninput=colorFromHex;$('accent-saturation').oninput=()=>{saturation=Number($('accent-saturation').value)/100;updateColor();};$('accent-brightness').oninput=()=>{brightness=Number($('accent-brightness').value)/100;updateColor();};
 const dial=$('accent-dial'),setPoint=event=>{const rect=dial.getBoundingClientRect();hue=(Math.atan2(event.clientY-rect.top-rect.height/2,event.clientX-rect.left-rect.width/2)*180/Math.PI+90+360)%360;updateColor();};
 dial.onpointerdown=event=>{dial.setPointerCapture(event.pointerId);setPoint(event);};dial.onpointermove=event=>{if(dial.hasPointerCapture(event.pointerId))setPoint(event);};dial.onkeydown=event=>{if(['ArrowLeft','ArrowDown','ArrowRight','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();hue=event.key==='Home'?0:event.key==='End'?359:(hue+(['ArrowLeft','ArrowDown'].includes(event.key)?-1:1)+360)%360;updateColor();}};
 $('settings-cancel').onclick=()=>modal.close();modal.addEventListener('close',()=>{secret.value='';draft=null;});
 $('settings-form').onsubmit=async event=>{event.preventDefault();capture();$('settings-save').disabled=true;try{if(!/^#[0-9a-f]{6}$/i.test($('settings-accent').value))throw new Error('Use a six-digit hex accent.');draft.accent=$('settings-accent').value;state=await api.updateAgentSettings({...draft,agent,version:state.version,...(secret.value?{secret:secret.value}:{}),clearSecret:clear.checked});applyAccent(state.accent);secret.value='';modal.close();await onChanged(state);}catch(error){$('settings-error').textContent=error.message;}finally{$('settings-save').disabled=false;}};
 api.onAgentSettings(value=>{state=value;applyAccent(value.accent);});
 return state;
}
